import { execFileSync } from "node:child_process"
import { readFileSync, writeFileSync } from "node:fs"
import { resolve } from "node:path"

const root = resolve(import.meta.dir, "..")
execFileSync(
  "cargo",
  [
    "+1.93.1",
    "build",
    "--locked",
    "--manifest-path",
    "native-search/Cargo.toml",
    "--target",
    "wasm32-unknown-unknown",
    "--release",
  ],
  {
    cwd: root,
    env: { ...process.env, RUSTFLAGS: "-C link-arg=-zstack-size=65536" },
    stdio: "inherit",
  },
)
const bytes = readFileSync(
  resolve(
    root,
    "native-search/target/wasm32-unknown-unknown/release/a01_exact_search.wasm",
  ),
)
writeFileSync(
  resolve(root, "lib/native-search/a01SearchWasmBytes.ts"),
  `// Generated by bun scripts/build-native-search.ts; do not edit.\n// The 64KB native stack keeps lazy instances small. No runtime fetch is used.\nexport const a01SearchWasmBase64 =\n  ${JSON.stringify(bytes.toString("base64"))}\n`,
)
const module = new WebAssembly.Module(bytes)
const instance = new WebAssembly.Instance(module)
const memory = instance.exports.memory as WebAssembly.Memory
console.log(
  JSON.stringify({
    wasmBytes: bytes.length,
    initialMemoryBytes: memory.buffer.byteLength,
  }),
)
