import { execFileSync } from "node:child_process"
import { createHash } from "node:crypto"
import { readFileSync, writeFileSync } from "node:fs"
import { resolve } from "node:path"

const root = resolve(import.meta.dir, "..")
execFileSync(
  "cargo",
  [
    "+1.93.1",
    "build",
    "--locked",
    "--manifest-path",
    "native-search-a03/Cargo.toml",
    "--target",
    "wasm32-unknown-unknown",
    "--release",
  ],
  {
    cwd: root,
    env: { ...process.env, RUSTFLAGS: "-C link-arg=-zstack-size=65536" },
    stdio: "inherit",
  },
)
const bytes = readFileSync(
  resolve(
    root,
    "native-search-a03/target/wasm32-unknown-unknown/release/a03_exact_search_preparation.wasm",
  ),
)
writeFileSync(
  resolve(root, "lib/native-search/a03SearchWasmBytes.ts"),
  `// Generated by bun scripts/build-native-a03-search.ts; do not edit.\n// Separate A03 module, 64KB native stack, synchronous host geometry, no runtime fetch.\nexport const a03SearchWasmBase64 =\n  ${JSON.stringify(bytes.toString("base64"))}\n`,
)
const module = new WebAssembly.Module(bytes)
const instance = new WebAssembly.Instance(module, {
  a03_host: {
    hypot: Math.hypot,
    footprint: () => {
      throw new Error("No active A03 owner")
    },
  },
})
const memory = instance.exports.memory as WebAssembly.Memory
console.log(
  JSON.stringify({
    wasmBytes: bytes.length,
    sha256: createHash("sha256").update(bytes).digest("hex"),
    initialMemoryBytes: memory.buffer.byteLength,
    imports: WebAssembly.Module.imports(module),
    exports: WebAssembly.Module.exports(module),
  }),
)
